### ISSUE TITLE
Provide stand-alone binary

### ISSUE THREAD

**Issue by qwertychouskie** [catid/WLANOptimizer#4]
Is there any chance of providing a stand-alone binary version?  This could be a really nice thing to run at startup on some systems.

**Comment by catid** [comment]
Good idea.  I have a Unity plugin for it but still need to build a demo app before release.  Will do some more work on this project soon

**Comment by qwertychouskie** [comment]
Cool, thanks!

**Comment by catid** [comment]
Pushed a binary you can use to test it, and CMakeLists to build it yourself

**Comment by qwertychouskie** [comment]
Thanks!
