### ISSUE TITLE
Could you please introduce the principle of WLAN transmission optimization in this project?

### ISSUE THREAD

**Issue by adcen0107** [catid/WLANOptimizer#8]
Could you please introduce the principle of WLAN transmission optimization in this project? 
Is it physical layer optimization or congestion control algorithm?

**Comment by catid** [comment]
It modifies two settings on the wlan adapters: (1) wlan_intf_opcode_media_streaming_mode=1 (2) wlan_intf_opcode_background_scan_enabled=0

The background scanning for available networks is the major cause of latency.

**Comment by adcen0107** [comment]
thx
